INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Alisa Childers' AND ch.name = 'Alisa Childers';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Alisa Childers' AND ch.name = 'Unshaken Faith Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Allen Parr' AND ch.name = 'The Beat with Allen Parr';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Andrew Soncrant' AND ch.name = 'Cultish';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jeff Durbin' AND ch.name = 'Cultish';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jeremiah Roberts' AND ch.name = 'Cultish';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Andrew Soncrant' AND ch.name = 'Apologia Studios';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jeff Durbin' AND ch.name = 'Apologia Studios';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jeremiah Roberts' AND ch.name = 'Apologia Studios';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Angela Scafidi' AND ch.name = 'Heaven & Healing Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Apostle Kathryn Krick' AND ch.name = 'Apostle Kathryn Krick';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Apostle Kathryn Krick' AND ch.name = 'Five-Fold Church';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Dr. Bobby Conway' AND ch.name = 'Christianity Still Makes Sense';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Brandon Cleaver' AND ch.name = 'Daily Disciple';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Brandon McGuire' AND ch.name = 'Daily Dose Of Wisdom';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Brittany Dawn' AND ch.name = 'Chiseled Hospitality';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Bryce Crawford' AND ch.name = 'Bryce Crawford Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Cameron Bertuzzi' AND ch.name = 'Capturing Christianity';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Cliffe Knechtle' AND ch.name = 'Give Me An Answer';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Stuart Knechtle' AND ch.name = 'Give Me An Answer';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Daniel Adams' AND ch.name = 'The Next Generation Ministries';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'David Wood' AND ch.name = 'Acts 17 Apologetics';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'David Wood' AND ch.name = 'Apologetics Roadshow';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Doreen Virtue' AND ch.name = 'Doreen Virtue';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Doreen Virtue' AND ch.name = 'New Age to New Heart Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jac Marino Chen' AND ch.name = 'New Age to New Heart Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jenn Nizza' AND ch.name = 'New Age to New Heart Podcast';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Dr. Frank Turek' AND ch.name = 'CrossExamined';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Dr. Gavin Ortlund' AND ch.name = 'TruthUnites';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Glen Scrivener' AND ch.name = 'Speak Life Media';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Greg Koukl' AND ch.name = 'Stand to Reason';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Tim Barnett' AND ch.name = 'Stand to Reason';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Greg Locke' AND ch.name = 'Global Vision Bible Church';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Isaiah Saldivar' AND ch.name = 'Isaiah Saldivar';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'J. Warner Wallace' AND ch.name = 'Cold-Case Christianity';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jimmy Wallace' AND ch.name = 'Cold-Case Christianity';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jac Marino Chen' AND ch.name = 'Jac Marino Chen';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jenn Nizza' AND ch.name = 'Ex-Psychic Saved';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jerren Lewis' AND ch.name = 'AoC Network';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Joe Kirby' AND ch.name = 'Off The Kirb Ministries';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Pastor Joe Schimmel' AND ch.name = 'Good Fight Ministries';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'John Lennox' AND ch.name = 'John Lennox';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'John Piper' AND ch.name = 'Desiring God';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jon Collins' AND ch.name = 'The Bible Project';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Tim Mackie' AND ch.name = 'The Bible Project';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Jon McCray' AND ch.name = 'Whaddo You Meme??';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Justin Brierley' AND ch.name = 'Premier Unbelievable?';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Justin Brierley' AND ch.name = 'Justin Brierley | Think Faith';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Ken Ham' AND ch.name = 'Answers in Genesis';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Laura Bragg' AND ch.name = 'Ex-New Ager Laura';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Marcus Rogers' AND ch.name = 'Marcus Rogers';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Matt Fradd' AND ch.name = 'Pints with Aquinas';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Melissa Dougherty' AND ch.name = 'Melissa Dougherty';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Michael Jones' AND ch.name = 'InspiringPhilosophy';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Michael Lofton' AND ch.name = 'Reason & Theology';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Michael Miller' AND ch.name = 'Remnant Radio';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Michael Roundtree' AND ch.name = 'Remnant Radio';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Mike Winger' AND ch.name = 'Mike Winger / BibleThinker';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Moriah Robinson' AND ch.name = 'Testify';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Preston Sprinkle' AND ch.name = 'Theology in the Raw';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Ray Comfort' AND ch.name = 'Living Waters';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Robert Lawrence Kuhn' AND ch.name = 'Closer To Truth';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Ruslan KD' AND ch.name = 'Ruslan KD';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'S. Michael Houdmann (Shea)' AND ch.name = 'Got Questions Ministries';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Scotty Mayer' AND ch.name = 'Little Light Studios';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Sean McDowell' AND ch.name = 'Sean McDowell';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Sean McDowell' AND ch.name = 'Think Biblically';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Steven Bancarz' AND ch.name = 'Reasons for Jesus';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Tim Barnett' AND ch.name = 'Red Pen Logic';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Todd Friel' AND ch.name = 'Wretched';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Trent Horn' AND ch.name = 'The Counsel of Trent';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Vlad Savchuk' AND ch.name = 'Hungry Generation';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Wes Huff' AND ch.name = 'Wes Huff';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Wes Huff' AND ch.name = 'Apologetics Canada';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Crossway (Institutional Network)' AND ch.name = 'Crossway';
INSERT INTO creator_channels (creator_id, channel_id) SELECT c.id, ch.id FROM creators c, channels ch WHERE c.name = 'Veritas Forum (Institutional Network)' AND ch.name = 'Veritas Forum';
