-- Converted from tags.sql
-- Old tags table became tags_internal.

INSERT INTO tags_internal (name) VALUES ('academic-apologetics');
INSERT INTO tags_internal (name) VALUES ('anti-progressive');
INSERT INTO tags_internal (name) VALUES ('apologist');
INSERT INTO tags_internal (name) VALUES ('baptist');
INSERT INTO tags_internal (name) VALUES ('bible-study');
INSERT INTO tags_internal (name) VALUES ('calvinist');
INSERT INTO tags_internal (name) VALUES ('case-making');
INSERT INTO tags_internal (name) VALUES ('catholic');
INSERT INTO tags_internal (name) VALUES ('cessationist');
INSERT INTO tags_internal (name) VALUES ('charismatic');
INSERT INTO tags_internal (name) VALUES ('christian-ethics');
INSERT INTO tags_internal (name) VALUES ('christian-hedonism');
INSERT INTO tags_internal (name) VALUES ('continuationist');
INSERT INTO tags_internal (name) VALUES ('cult-critique');
INSERT INTO tags_internal (name) VALUES ('cultural-commentary');
INSERT INTO tags_internal (name) VALUES ('deconstruction-response');
INSERT INTO tags_internal (name) VALUES ('deliverance');
INSERT INTO tags_internal (name) VALUES ('discernment');
INSERT INTO tags_internal (name) VALUES ('dispensational');
INSERT INTO tags_internal (name) VALUES ('documentary');
INSERT INTO tags_internal (name) VALUES ('evolutionary-creationist');
INSERT INTO tags_internal (name) VALUES ('ex-new-age');
INSERT INTO tags_internal (name) VALUES ('inerrancy');
INSERT INTO tags_internal (name) VALUES ('lifestyle');
INSERT INTO tags_internal (name) VALUES ('non-denominational');
INSERT INTO tags_internal (name) VALUES ('old-earth-creationist');
INSERT INTO tags_internal (name) VALUES ('pentecostal');
INSERT INTO tags_internal (name) VALUES ('postmillennial');
INSERT INTO tags_internal (name) VALUES ('premillennial');
INSERT INTO tags_internal (name) VALUES ('reformed');
INSERT INTO tags_internal (name) VALUES ('science-and-faith');
INSERT INTO tags_internal (name) VALUES ('spiritual-warfare');
INSERT INTO tags_internal (name) VALUES ('street-evangelism');
INSERT INTO tags_internal (name) VALUES ('thomistic');
INSERT INTO tags_internal (name) VALUES ('young-earth-creationist');
